version: '3.4'

services:
  migrations:
    build:
      context: ../../
      dockerfile: templates/service/database/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - IdentityServer_DB=TodoListModule_Identity
      - TodoListModule_DB=TodoListModule_ModuleDb
      - SA_PASSWORD=yourStrong(!)Password
